server:
  port: 8998

spring:
  profiles:
    active: secret
  ############
  application:
    name: microhisto
  data:
    mongodb:
      uri: mongodb://localhost:27017/histo
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Configuration du logging
logging:
  level:
    root: ERROR # Niveau de log par défaut pour toutes les classes non spécifiées
    org.medilabo: INFO # Niveau INFO pour les classes du package org.medilabo
    org.medilabo.microhisto: debug # Niveau DEBUG pour les logs spécifiques de l'application microhisto
    org.springframework.boot.web.embedded.tomcat: INFO # Pour les logs Tomcat embarqué
    org.springframework.security: DEBUG # Pour les logs détaillés de Spring Security (utile pour JWT)
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
