server:
  port: 8998

spring:
  profiles:
    active: secret
  ############
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=Authorization,
      routes:
        - id: patient-service
          uri: http://localhost:8999
          predicates:
            - Path=/patients/**
        - id: historique-service
          uri: http://localhost:8998
          predicates:
            - Path=/hist/**
        - id: risque-service
          uri: http://localhost:8997
          predicates:
            - Path=/evaluer/**
  ############
  application:
    name: microhisto
  data:
    mongodb:
      uri: mongodb://localhost:27017/histo
      auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG
