server:
  port: 8996

spring:
  application:
    name: microapigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: micropatient
          uri: lb://MICROPATIENT
          predicates:
            - Path=/patients/**
          filters:
            - StripPrefix=0
        - id: microhisto
          uri: lb://MICROHISTO
          predicates:
            - Path=/hist/**
          filters:
            - StripPrefix=0
        #- id: auth-service
        #  uri: lb://MICROHISTO
        #  predicates:
        #    - Path=/auth/**
        #  filters:
        #    - StripPrefix=0
        - id: microrisque
          uri: lb://MICRORISQUE
          predicates:
            - Path=/evaluer/**
          filters:
            - StripPrefix=0

eureka:
  client:
    serviceUrl:
      defaultZone: http://microeureka-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true   # Utilisation de l’adresse IP pour l’enregistrement Eureka

logging:
  level:
    root: ERROR
    org.medilabo: INFO
    org.springframework.boot.web.embedded.tomcat: INFO
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

jwt:
  header: Authorization
  secret: my-very-secret-key