server:
  port: 8999

jwt:
    secret: "secret-key"

spring:
  #cloud:
    #gateway:
      #      routes:
    # - id: patient-service
      #   uri: http://localhost:8999
      #   predicates:
      #      - Path=/patients/**
      #      - id: historique-service
      #         uri: http://localhost:8998
      #          predicates:
      #       - Path=/hist/**
    #    - id: risque-service
    #          uri: http://localhost:8997
    #          predicates:
#            - Path=/risque/**


##############################
    application:
      name: micropatient
    datasource:
      url: jdbc:mysql://localhost:3306/medilabo
      username: root
      password: rootroot_2024
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true

  #logging:
      #  level:
  #   org.springframework.web: DEBUG

  ##############################

  #security:
      #  oauth2:
        #   resource-server:
        #    jwt: secret-key
        ##  issuer-uri: https://medilabo.org/